// export const SELECT_CHANNEL = "SELECT_CHANNEL";
export const UPDATE_CHANNEL = "UPDATE_CHANNEL";
export const GET_FRIENDS = "GET_FRIENDS";
export const GET_USER = "GET_USER";
export const TOGGLE_FRIENDS = "TOGGLE_FRIENDS";
export const TOGGLE_CHAT = "TOGGLE_CHAT";
export const UPDATE_MESSAGES = 'UPDATE_MESSAGES';
export const TOGGLE_NEWCHAT = "TOGGLE_NEWCHAT"